apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-oppslag-journalpost-id
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  {{ ingresses }}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling
  kafka:
    pool: {{ kafka_pool }}
