apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-oppslag-journalpost-id
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  {{ ingresses }}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: oppslag-journalpostid
        diskAutoresize: true
        diskType: SSD
        highAvailability: {{ db.highAvailability }}
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        pointInTimeRecovery: {{ db.pointInTimeRecovery }}
        tier: {{ db.tier }}
        type: POSTGRES_15
